<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>NgolExt.NativeHook.Api</AssemblyName>
    <RootNamespace>NgolExt.NativeHook</RootNamespace>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.0.0</Version>
    <Deterministic>true</Deterministic>
    <PathMap>$(MSBuildThisFileDirectory)=/_/</PathMap>
  </PropertyGroup>

</Project>
